spring.application.name=mycoolapp
dinosour.movie=jurassic world

#USE "," AS DEMILITER FOR EVERY SPECIFIC INDIVIDUAL ENDPOINTS TO INCLUDE
#management.endpoints.web.exposure.include=health,info

#USE JUST "*" TO INLCUDE ALL ENDPOINTS
management.endpoints.web.exposure.include=*

#TO EXCLUDE SPECIFIC ENDPOINTS
management.endpoints.web.exposure.exclude=health,info

#CUSTOME SPRING SECURITY CREDENTIALS
spring.security.user.name=loki
spring.security.user.password=4578

management.info.env.enabled=true

info.app.name=MyApp
info.app.description=My crazy fun App